name: CI setup for Go
on: #on event keyword
  push:
    branches: [main] #identifying branch
    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest #specify os in virtaul machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! #run terminal command

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
    - name: show Go Version # verify that go is install
      run: |
        go version # show the go version
    - name: Checkout our codes
      uses: actions/checkout@v2
      
    - name: Check file system
      run: |
        ls
        cat calc.go # prints the content of calc.go
        
    - name: Checkout private repo remotely
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample # the hidden repo i am rtying to access
        path: remoteRepo # Folder to save to in my virtual env
        token: ${{ secrets.GO_SECRET }} #pass to enter the remote hidden repo
        
    - name: Show hidden files
      run: |
        cd virtualRepoFolder # to access the foler of interest in my virtual env
        ls
        cat myText.txt
        cd ..
    
    
